### ISSUE TITLE
Add markdown (or kramdown) support on site

### ISSUE THREAD

**Issue by dougproctor** [dougproctor/dougproctor.github.io#11]
One last thing after we get the site sizing squared away -- could you please add markdown support to the site? Should be extremely quick, and will make it easier to keep things formatted appropriately going forward.

**Comment by dougproctor** [comment]
Note that when I try to add markdown styles to pages (e.g. "FAQ"), it does not seem to work.

**Comment by romakuchukov** [comment]
You have to rename it `faq.md` but since we already have `faq.html` it takes precedence over `faq.md`. Try naming it `faq2.md` or something like that. And when you're ready just switch the names.

**Comment by romakuchukov** [comment]
Another thing you can do is this. You can still name the file `faq.md` just add a different `permalink` field, like so (see the screenshot):
![Screen Shot 2020-12-23 at 10 31 21 AM](https://user-images.githubusercontent.com/804157/103012920-4a17df00-450a-11eb-8792-d98597093323.JPG)
and then just go to /faq2 page. And once it's ready remove the permalink and the old `faq.html` file.
