### ISSUE TITLE
Add Tiny Talk logo as favicon

### ISSUE THREAD

**Issue by dougproctor** [dougproctor/dougproctor.github.io#12]

**Comment by romakuchukov** [comment]
Favicon is in. It shows up on the site. I can see it right now. Check to see if it shows up for you, plz.

**Comment by dougproctor** [comment]
Yep, we are g2g here - looks great - closing.

![image](https://user-images.githubusercontent.com/1671916/103011726-a0c7ed80-44f7-11eb-8b9a-557d02231c61.png)
