### ISSUE TITLE
Sticky nav-bar

### ISSUE THREAD

**Issue by dougproctor** [dougproctor/dougproctor.github.io#4]
Currently, the nav-bar does not stick at the top of the screen when scrolling.

We should update it so that the nav-bar sticks to the top of the screen when user scrolls down (on both mobile and desktop)

**Comment by romakuchukov** [comment]
The navbar is now sticky. Try it out.

**Comment by romakuchukov** [comment]
The last comment says "closing", but this issue is still open. Can you look into this?

**Comment by dougproctor** [comment]
Closed!
