### ISSUE TITLE
Reduce size of (1) iOS and Android phone decals + download buttons and (2) footer text

### ISSUE THREAD

**Issue by dougproctor** [dougproctor/dougproctor.github.io#8]
Please see Houseparty website for rough dimensions that we should use for the phone decals and footer

Screenshot below for reference:

![image](https://user-images.githubusercontent.com/1671916/102738315-f38e8300-4306-11eb-9506-76978b6a3faa.png)

**Comment by romakuchukov** [comment]
Can you double-check this one? And report back. Should be good now.

**Comment by dougproctor** [comment]
Yep - we are g2g here now - closing
