### ISSUE TITLE
Reduce FAQ (and Download, Privacy, Terms) page dimensions

### ISSUE THREAD

**Issue by dougproctor** [dougproctor/dougproctor.github.io#9]
Tiny Talk page content dimensions on FAQ is a little bit too large.

We should change page dimensions to be closer to what Houseparty's site looks like (see screenshot below):

![image](https://user-images.githubusercontent.com/1671916/102738404-3e0fff80-4307-11eb-88b9-5a3a1d870d8e.png)

**Comment by romakuchukov** [comment]
Double-check the width of the content for these pages, will ya? Should be good to go.

**Comment by dougproctor** [comment]
Yep - we are g2g here now - closing

**Comment by dougproctor** [comment]
Yep, confirmed showing up - looks great. Closing

![image](https://user-images.githubusercontent.com/1671916/103011687-960d5880-44f7-11eb-808b-6c5ded958b27.png)
